/* ============================================================
   Wavelength — Default Word Spectrums
   ★ Krit's vibe coding ★

   Each entry is a polar pair: { left, right }
   Provided in three languages: en (English), th (ไทย), ja (日本語)

   The deck is exposed on window.WAVELENGTH_WORDS so index.html
   can read it without any module bundler — perfect for GitHub Pages.
   ============================================================ */

window.WAVELENGTH_WORDS = {
  en: [
    { left: "Hot",            right: "Cold" },
    { left: "Cheap",          right: "Expensive" },
    { left: "Underrated",     right: "Overrated" },
    { left: "Round",          right: "Pointy" },
    { left: "Useless",        right: "Useful" },
    { left: "Scary",          right: "Comforting" },
    { left: "Common",         right: "Rare" },
    { left: "Quiet",          right: "Loud" },
    { left: "Old fashioned",  right: "Modern" },
    { left: "Forgettable",    right: "Memorable" },
    { left: "Weird",          right: "Normal" },
    { left: "Healthy",        right: "Unhealthy" },
    { left: "Casual",         right: "Formal" },
    { left: "Wholesome",      right: "Sinful" },
    { left: "Ugly",           right: "Beautiful" },
    { left: "Boring",         right: "Exciting" },
    { left: "Fragile",        right: "Sturdy" },
    { left: "Simple",         right: "Complicated" },
    { left: "Dangerous",      right: "Safe" },
    { left: "Temporary",      right: "Permanent" },
    { left: "Overdressed",    right: "Underdressed" },
    { left: "A bad habit",    right: "A good habit" },
    { left: "Fantasy",        right: "Sci-fi" },
    { left: "Talent",         right: "Hard work" },
    { left: "Introvert",      right: "Extrovert" },
    { left: "Guilty pleasure",right: "Respectable taste" },
    { left: "Underground",    right: "Mainstream" },
    { left: "A want",         right: "A need" },
    { left: "Disgusting",     right: "Delicious" },
    { left: "Easy to make",   right: "Hard to make" },
    { left: "Villain",        right: "Hero" },
    { left: "Stops a party",  right: "Starts a party" },
    { left: "Forbidden",      right: "Encouraged" },
    { left: "Dry",            right: "Wet" },
    { left: "Useless skill",  right: "Survival skill" },
    { left: "Smells bad",     right: "Smells good" },
    { left: "Childish",       right: "Mature" },
    { left: "A flaw",         right: "A feature" },
    { left: "Overpriced",     right: "Worth every penny" },
    { left: "Trash",          right: "Treasure" }
  ],

  th: [
    { left: "ร้อน",              right: "เย็น" },
    { left: "ถูก",               right: "แพง" },
    { left: "ถูกมองข้าม",        right: "ถูกยกย่องเกินจริง" },
    { left: "กลม",               right: "แหลม" },
    { left: "ไร้ประโยชน์",       right: "มีประโยชน์" },
    { left: "น่ากลัว",           right: "อบอุ่นใจ" },
    { left: "พบเห็นทั่วไป",      right: "หายาก" },
    { left: "เงียบ",             right: "เสียงดัง" },
    { left: "ล้าสมัย",           right: "ทันสมัย" },
    { left: "ลืมง่าย",           right: "น่าจดจำ" },
    { left: "แปลก",              right: "ปกติ" },
    { left: "ดีต่อสุขภาพ",       right: "ทำลายสุขภาพ" },
    { left: "สบายๆ",             right: "เป็นทางการ" },
    { left: "ใสสะอาด",           right: "เลวร้าย" },
    { left: "น่าเกลียด",         right: "สวยงาม" },
    { left: "น่าเบื่อ",          right: "น่าตื่นเต้น" },
    { left: "เปราะบาง",          right: "แข็งแรงทนทาน" },
    { left: "เรียบง่าย",         right: "ซับซ้อน" },
    { left: "อันตราย",           right: "ปลอดภัย" },
    { left: "ชั่วคราว",          right: "ถาวร" },
    { left: "แต่งเกินงาน",       right: "แต่งน้อยเกินไป" },
    { left: "นิสัยเสีย",         right: "นิสัยดี" },
    { left: "แฟนตาซี",           right: "ไซไฟ" },
    { left: "พรสวรรค์",          right: "ความพยายาม" },
    { left: "คนเก็บตัว",         right: "คนเปิดเผย" },
    { left: "ความสุขที่แอบรู้สึกผิด", right: "รสนิยมที่น่ายกย่อง" },
    { left: "นอกกระแส",          right: "กระแสหลัก" },
    { left: "สิ่งที่อยากได้",    right: "สิ่งที่จำเป็น" },
    { left: "น่าขยะแขยง",        right: "อร่อย" },
    { left: "ทำง่าย",            right: "ทำยาก" },
    { left: "ตัวร้าย",           right: "ฮีโร่" },
    { left: "ทำให้ปาร์ตี้จบ",    right: "ทำให้ปาร์ตี้สนุก" },
    { left: "ต้องห้าม",          right: "ได้รับการสนับสนุน" },
    { left: "แห้ง",              right: "เปียก" },
    { left: "ทักษะไร้ค่า",       right: "ทักษะเอาตัวรอด" },
    { left: "เหม็น",             right: "หอม" },
    { left: "เด็กๆ",             right: "เป็นผู้ใหญ่" },
    { left: "ข้อเสีย",           right: "จุดเด่น" },
    { left: "ราคาแพงเกินไป",     right: "คุ้มทุกบาท" },
    { left: "ขยะ",               right: "ของล้ำค่า" }
  ],

  ja: [
    { left: "熱い",             right: "冷たい" },
    { left: "安い",             right: "高い" },
    { left: "過小評価",         right: "過大評価" },
    { left: "丸い",             right: "尖っている" },
    { left: "役に立たない",     right: "役に立つ" },
    { left: "怖い",             right: "安心する" },
    { left: "ありふれた",       right: "珍しい" },
    { left: "静か",             right: "うるさい" },
    { left: "古風",             right: "現代的" },
    { left: "忘れやすい",       right: "印象的" },
    { left: "変わってる",       right: "普通" },
    { left: "健康的",           right: "不健康" },
    { left: "カジュアル",       right: "フォーマル" },
    { left: "健全",             right: "背徳的" },
    { left: "醜い",             right: "美しい" },
    { left: "退屈",             right: "わくわくする" },
    { left: "壊れやすい",       right: "丈夫" },
    { left: "単純",             right: "複雑" },
    { left: "危険",             right: "安全" },
    { left: "一時的",           right: "永続的" },
    { left: "着飾りすぎ",       right: "ラフすぎ" },
    { left: "悪い習慣",         right: "良い習慣" },
    { left: "ファンタジー",     right: "SF" },
    { left: "才能",             right: "努力" },
    { left: "内向的",           right: "外向的" },
    { left: "後ろめたい趣味",   right: "立派な趣味" },
    { left: "アンダーグラウンド", right: "メジャー" },
    { left: "欲しいもの",       right: "必要なもの" },
    { left: "気持ち悪い",       right: "おいしい" },
    { left: "作るのが簡単",     right: "作るのが難しい" },
    { left: "悪役",             right: "ヒーロー" },
    { left: "場をしらけさせる", right: "場を盛り上げる" },
    { left: "禁止",             right: "推奨" },
    { left: "乾いている",       right: "濡れている" },
    { left: "無駄なスキル",     right: "生存スキル" },
    { left: "臭い",             right: "良い香り" },
    { left: "子供っぽい",       right: "大人っぽい" },
    { left: "欠点",             right: "長所" },
    { left: "割高",             right: "値段以上の価値" },
    { left: "ゴミ",             right: "宝物" }
  ]
};
